name: Build and Push Services

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push API Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./API_Gateway
          push: true
          tags: anujakalahara99/api-gateway:latest

      - name: Build & Push Codespace Service
        uses: docker/build-push-action@v5
        with:
          context: ./Codespace_Service
          push: true
          tags: anujakalahara99/codespace-service:latest

      - name: Build & Push WS Server
        uses: docker/build-push-action@v5
        with:
          context: ./WS_Server
          push: true
          tags: anujakalahara99/ws-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/app
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans
